local module = {
        Coins = 50,
        Level = 0,
        Exp = 0,
        Rank = "Novice",
        Inventory = {
               Burger =  {
                        Name = "Burger",
                        Amount = 1,
                        Upgrades = {}
                }
        },
      
        Food = {},
        Settings = {
            Sound = true,
            Music = true,
        }
        

}

return module